FROM python:3.12-slim

WORKDIR /api

# Update system packages to reduce vulnerabilities
RUN apt-get update && apt-get upgrade -y && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY ../requirements.txt /api/
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY ../Model /api/Model
COPY ./main.py /api/main.py

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
